services:
  lecture-worker:
    build: .
    container_name: lecture-notes-bot
    env_file:
      - .env
    envirounments:
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - ./data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1.0G
          cpus: "1.5"
